import Head from 'next/head'
import {GraphQLClient,gql} from 'graphql-request'
const graphcms = new GraphQLClient("https://api-eu-central-1.hygraph.com/v2/cl81tjdr31urc01t1dohh2blb/master");

import WebsiteCard from '../components/WebsiteCard';
import TopNavbar from '../components/TopNavbar';

const QUERY = gql`
  {
    websites{
      name,
      slug,
      heroPhoto{
        url
      }
      content{
        html
      },
      description
    }
  }
`;

export async function  getStaticProps(){
  const { websites } = await graphcms.request(QUERY);
  return{
    props:{
      websites,
    },
    revalidate:10,
  }
}

export default function Home({websites}) {

  return (
    <div>
      <Head>
        <title>Filip Kotłowski - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <TopNavbar />
        <h1>Hi, my name is Filip Kotłowski</h1>
        <h3>web developer</h3>
        <h5>based in Opole, Poland</h5>
        {websites.map((website)=>(
          <WebsiteCard  title={website.name}
                        heroPhoto={website.heroPhoto}
                        slug={website.slug}
          />
        ))}
      </main>

    </div>
  )
}
