import Head from 'next/head'
import {GraphQLClient,gql} from 'graphql-request'
const graphcms = new GraphQLClient("https://api-eu-central-1.hygraph.com/v2/cl81tjdr31urc01t1dohh2blb/master");

import WebsiteCard from '../components/WebsiteCard';
import TopNavbar from '../components/TopNavbar';
import HeroSection from '../sections/HeroSection';
import AboutSection from '../sections/AboutSection';
import WorkSection from '../sections/WorkSection';

const QUERY = gql`
  {
    websites{
      name,
      slug,
      heroPhoto{
        url
      }
      content{
        html
      },
      description
    }
  }
`;

export async function  getStaticProps(){
  const { websites } = await graphcms.request(QUERY);
  return{
    props:{
      websites,
    },
    revalidate:10,
  }
}

export default function Home({websites}) {

  return (
    <div>
      <Head>
        <title>Filip Kotłowski - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <TopNavbar />
        <HeroSection />
        <AboutSection />
        <WorkSection content=
        {websites.map((website)=>(
          <WebsiteCard  title={website.name}
                        heroPhoto={website.heroPhoto}
                        slug={website.slug}
                        description={website.description}
          />
        ))} />
      </main>

    </div>
  )
}